//peole
const FETCHING_PEOPLE = 'FETCHING_PEOPLE'
const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS'
const FETCHING_PEOPLE_FAILURE = 'FETCHING_PEOPLE_FAILURE'

//validation
const VALIDATE_USER = 'VALIDATE_USER'
const VALIDATE_USER_SUCCESS = 'VALIDATE_USER_SUCCESS'
const VALIDATE_USER_FAILURE = 'VALIDATE_USER_FAILURE'

//users
const FETCH_USER = 'FETCH_USER'
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

const POST_USER = 'POST_USER'
const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
const POST_USER_FAILURE = 'POST_USER_FAILURE'

//employee
const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE'
const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS'
const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE'

const POST_EMPLOYEE = 'POST_EMPLOYEE'
const POST_EMPLOYEE_SUCCESS = 'POST_EMPLOYEE_SUCCESS'
const POST_EMPLOYEE_FAILURE = 'POST_EMPLOYEE_FAILURE'

const FETCH_RATING = 'FETCH_RATING'
const FETCH_RATING_SUCCESS = 'FETCH_RATING_SUCCESS'
const FETCH_RATING_FAILURE = 'FETCH_RATING_FAILURE'

//master data
const FETCH_MASTER = 'FETCH_MASTER'
const FETCH_MASTER_SUCCESS = 'FETCH_MASTER_SUCCESS'
const FETCH_MASTER_FAILURE = 'FETCH_MASTER_FAILURE'


//report
const FETCH_REPORT = 'FETCH_REPORT'
const FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS'
const FETCH_REPORT_FAILURE = 'FETCH_REPORT_FAILURE'

//rating
const POST_RATING = 'POST_RATING'
const POST_RATING_SUCCESS = 'POST_RATING_SUCCESS'
const POST_RATING_FAILURE = 'POST_RATING_FAILURE'


//department
const FETCH_DEPARTMENT = 'FETCH_DEPARTMENT'
const FETCH_DEPARTMENT_SUCCESS = 'FETCH_DEPARTMENT_SUCCESS'
const FETCH_DEPARTMENT_FAILURE = 'FETCH_DEPARTMENT_FAILURE'

const POST_DEPARTMENT = 'POST_DEPARTMENT'
const POST_DEPARTMENT_SUCCESS = 'POST_DEPARTMENT_SUCCESS'
const POST_DEPARTMENT_FAILURE = 'POST_DEPARTMENT_FAILURE'

//designatiom
const FETCH_DESIGNATION = 'FETCH_DESIGNATION'
const FETCH_DESIGNATION_SUCCESS = 'FETCH_DESIGNATION_SUCCESS'
const FETCH_DESIGNATION_FAILURE = 'FETCH_DESIGNATION_FAILURE'

const POST_DESIGNATION = 'POST_DESIGNATION'
const POST_DESIGNATION_SUCCESS = 'POST_DESIGNATION_SUCCESS'
const POST_DESIGNATION_FAILURE = 'POST_DESIGNATION_FAILURE'

//baseurl
const BASE_URL_LOCAL = 'http://localhost:3000/'
const BASE_URL_LIVE = 'http://13.58.178.232:3000/'
const BASE_URL = BASE_URL_LIVE//BASE_URL_LOCAL

export {
    BASE_URL,

    FETCHING_PEOPLE, FETCHING_PEOPLE_SUCCESS, FETCHING_PEOPLE_FAILURE,

    FETCH_USER, FETCH_USER_SUCCESS, FETCH_USER_FAILURE,
    POST_USER, POST_USER_SUCCESS, POST_USER_FAILURE,
    VALIDATE_USER_SUCCESS, VALIDATE_USER_FAILURE, VALIDATE_USER,

    FETCH_EMPLOYEE, FETCH_EMPLOYEE_SUCCESS, FETCH_EMPLOYEE_FAILURE,
    POST_EMPLOYEE, POST_EMPLOYEE_SUCCESS, POST_EMPLOYEE_FAILURE,

    FETCH_RATING, FETCH_RATING_SUCCESS, FETCH_RATING_FAILURE,
    POST_RATING, POST_RATING_SUCCESS, POST_RATING_FAILURE,

    FETCH_MASTER, FETCH_MASTER_SUCCESS, FETCH_MASTER_FAILURE,

    FETCH_REPORT, FETCH_REPORT_SUCCESS, FETCH_REPORT_FAILURE,


    FETCH_DEPARTMENT, FETCH_DEPARTMENT_SUCCESS, FETCH_DEPARTMENT_FAILURE,
    POST_DEPARTMENT, POST_DEPARTMENT_SUCCESS, POST_DEPARTMENT_FAILURE,

    FETCH_DESIGNATION, FETCH_DESIGNATION_SUCCESS, FETCH_DESIGNATION_FAILURE,
    POST_DESIGNATION, POST_DESIGNATION_SUCCESS, POST_DESIGNATION_FAILURE
}